[package]
name = "inoda-core"
version = "0.1.0"
edition = "2024"

[dependencies]
cosmic-text = "0.12"
cssparser = "0.36.0"
generational-arena = "0.2.9"
html5ever = "0.38.0"
markup5ever = "0.38.0"
rquickjs = { version = "0.11.0", features = ["classes"] }
string_cache = "0.9.0"
taffy = "0.9.2"
