[package]
name = "inoda-core"
version = "0.1.0"
edition = "2024"

[dependencies]
cssparser = "0.36.0"
femtovg = "0.20.3"
generational-arena = "0.2.9"
html5ever = "0.38.0"
markup5ever = "0.38.0"
rquickjs = { version = "0.11.0", features = ["classes"] }
taffy = "0.9.2"
